export type AgdsErrorCode =
  | "DOCUMENT_PUBLIC_ID_CONFLICT"
  | "GRAPH_BROKEN_LINK"
  | "LLM_RATE_LIMITED"
  | "QUERY_WRITE_FORBIDDEN"
  | "RESOLVE_NOT_FOUND"
  | "LOCK_CONFLICT"
  | "MANAGED_SECTION_CONFLICT";
